name: Build project

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          usedocker: true